# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-29 01:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantitad', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Modelo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Marca')),
            ],
        ),
        migrations.CreateModel(
            name='Partes_carroceria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('color', models.CharField(max_length=30)),
                ('nivel_m', models.IntegerField()),
                ('carro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Carro')),
            ],
        ),
        migrations.CreateModel(
            name='Partes_electricas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('carro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Carro')),
            ],
        ),
        migrations.CreateModel(
            name='Partes_maestro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(choices=[('Electricas', 'Electricas'), ('Mecanicas', 'Mecanicas'), ('Carroceria', 'Carroceria')], max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Partes_mecanicas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('motor', models.CharField(choices=[('4', '4'), ('6', '6'), ('8', '8')], max_length=30)),
                ('transmision', models.CharField(choices=[('Manual', 'Manual'), ('Automatica', 'Automatica')], max_length=30)),
                ('carro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Carro')),
                ('parte', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='home.Partes_maestro')),
            ],
        ),
        migrations.AddField(
            model_name='partes_electricas',
            name='parte',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='home.Partes_maestro'),
        ),
        migrations.AddField(
            model_name='partes_carroceria',
            name='parte',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='home.Partes_maestro'),
        ),
        migrations.AddField(
            model_name='carro',
            name='marca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Marca'),
        ),
        migrations.AddField(
            model_name='carro',
            name='modelo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Modelo'),
        ),
    ]
